name = "DistanceTransformsPy"
uuid = "d85f584c-7717-483c-8218-10621e78a8b8"
authors = ["Dale-Black <djblack@uci.edu> and contributors"]
version = "0.1.0"

[deps]
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"

[compat]
PythonCall = "0.9.15"
julia = "1.9"

[extras]
ImageMorphology = "787d08f9-d448-5407-9aad-5290dd7ab264"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["ImageMorphology", "Test"]
